image: node:10.19.0

pipelines:
  branches:
    develop:
      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - npm install
            - npm install -g firebase-tools
            - npm run build
            - ./scripts/ci/setup.sh
            - export $(cat ENVIRONMENT_VARIABLES.txt | xargs)
            - firebase deploy --token=$FIREBASE_TOKEN --project react-project-1555f --only hosting:satpass --non-interactive

